version: '3.8'

services:
  api:
    image: solid-api:latest
    build:
      context: .
      dockerfile: apps/api/Dockerfile  # Ruta al Dockerfile de la API
      args:
        DATABASE_URL: ${DATABASE_URL}  # Aquí estás pasando la variable al Dockerfile como un ARG
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Asegúrate de que el contenedor tenga acceso a la variable de entorno en ejecución
    env_file:
      - .env  # Asegúrate de que tu .env esté en la raíz y que contenga la variable DATABASE_URL

  web:
    image: solid-web:latest
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        BUCKET_URL: ${BUCKET_URL}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - BUCKET_URL=${BUCKET_URL}
      - AUTH_SECRET=${AUTH_SECRET}
    env_file:
      - .env  # Asegúrate de que tu .env esté en la raíz y que contenga la variable DATABASE_URL
    # depends_on:
    #   - api